version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      # Add any other volumes you need for your application
