version: '3'

services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_container
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
      # Add any other volumes you need for your application
  
  db:
    container_name: mysql_container
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: 'hive'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'Test2001'
    ports:
      - '9906:3306'